Changes to 2.7
UlisseMini/understanding-analysis-solutions pull request #15
Opened 2022-05-01 23:57 UTC by jesseli2002

- 2.7.4d), alternating series test requires that |a_n| be decreasing
![image](https://user-images.githubusercontent.com/24727586/166169890-41c46518-3cdf-46d8-93b9-68ac33625199.png)
- 2.7.10b) was missing whether the product converges to zero or not
- Spent like 2 hours trying to reason about the necessary behaviour in 2.7.11 before finding a solution

2022-05-03 10:16 UTC, UlisseMini requested changes
The example you give for `x_n` converges by a comparison test with `1/n` (same reason `sum (-1)^n/n` converges). I think the correct solution uses the comparison test to show it's impossible.

2022-05-03 10:18 UTC, UlisseMini commented
> Spent like 2 hours trying to reason about the necessary behaviour in 2.7.11 before finding a solution

Haha same, minus the "finding a solution" part

2022-05-03 10:26 UTC, UlisseMini approved these changes
I'm surprised the products converge to zero, intuitively they seemed to decrease too slowly. I guess that's what I deserve for skipping it because it looked "trivial" ;)

2022-05-03 19:09 UTC, jesseli2002 commented
> The example you give for `x_n` converges by a comparison test with `1/n` (same reason `sum (-1)^n/n` converges). I think the correct solution uses the comparison test to show it's impossible.

Assuming this refers to 2.7.4d) - If `x_n` defined as 
![image](https://user-images.githubusercontent.com/24727586/166524983-0de6f6cb-5cf9-4236-ad89-1a8bd1678e0b.png)
then `(-1)^n x_n`  would be `0, 1/2, 0, 1/4, 0, 1/6, 0, 1/8, 0, 1/10, 0, ...` which diverges, no?

2022-05-04 11:34 UTC, UlisseMini commented
Oh I see now, you're right `x_n` diverges because the `(-1)^n`'s are all in the same direction, the first time I read it wrong

2022-05-04 11:34 UTC, UlisseMini approved these changes

2022-05-04 11:34 UTC, merged